def get_censor_list() -> list:
    return [
        "porn",
        "cumporn",
        "chaturbate",
        "sex",
        "nude",
        "naked",
        "fap",
        "squirt",
        "bondage",
        "boobs",
        "pussy",
        "nipple"
    ]


def get_skip_types() -> list:
    return [
        "jpg",
        "jpeg",
        "png",
        "gif",
        "pdf",
        "doc",
        "docx",
        "ppt",
        "pptx",
        "xls",
        "xlsx",
        "zip",
        "rar",
        "tar",
        "bmp",
        "webp",
        "tiff",
        "svg",
        "mp4",
        "avi",
        "mov",
        "wmv",
        "flv",
        "mkv",
        "mp3",
        "wav",
        "flac",
        "aac",
        "ogg",
        "wma",
        "m4a",
    ]
